
lane :customize_build do |options|
  welcome_message = options[:welcome_message] || 'Hello World!'
  background_color = options[:background_color] || '#FFFFFFFF'

  update_plist(
    plist_path: './AppExample/AppExample/configurations.plist',
    block: proc do |plist|
      plist[:WelcomeMessage] = welcome_message
      plist[:BackgroundHexColor] = background_color
    end
  )
end

lane :build_custom_app do |options|
  customize_build options
  xcodebuild(
    {
      clean: true,
      build: true,
      output_name: "simulatorApp.ipa",
      project: './AppExample/AppExample.xcodeproj',
      scheme: 'AppExample',
      configuration: "SimulatorBuild",
      sdk: "iphonesimulator",
      destination: "platform=iOS Simulator,name=iPhone 8",
      xcargs: "ONLY_ACTIVE_ARCH=NO"
    }
  )
end
